# Generated by Django 3.1.3 on 2020-11-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mugs',
            new_name='Mug',
        ),
        migrations.AlterModelOptions(
            name='mug',
            options={'verbose_name_plural': 'Mugs'},
        ),
    ]
