# Generated by Django 3.1.3 on 2020-11-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugs', '0002_auto_20201117_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='mug',
            name='on_sale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
