# Generated by Django 3.1.3 on 2020-11-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugs', '0006_mug_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mug',
            name='date',
        ),
    ]
